// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PSInzinerija1.Data.ApplicationDbContext;

#nullable disable

namespace PSInzinerija1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241006122244_AspNetIdentity")]
    partial class AspNetIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("PSInzinerija1.Models.HighScoresEntry", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("game_id");

                    b.Property<int>("HighScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("high_score");

                    b.HasKey("Id", "GameId");

                    b.ToTable("high_scores");
                });
#pragma warning restore 612, 618
        }
    }
}
