# Use the official Nginx image as the base
FROM nginx:latest

# Copy your custom nginx.conf file into the container
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

# Expose the necessary ports
EXPOSE 80
